from . import community_master
from . import courses_master
from . import district_master
from . import institution_group_master
from . import last_studied_institutions
from . import place_city_master
from . import reference_master
from . import student_admission
from . import taluk_master
from . import admission_confirmation
from . import education_qualification
from . import stages_master
from . import grade_master
from . import degree_master
from . import student_details
from . import special_quota
from . import token_fees
from . import admission_list
from . import res_partner
from . import section_master
from . import concession
from . import stream_master
from . import semester_master
from . import quota_master
from . import courses_and_college_master
from . import degree_level_master
from . import product_product
from . import account_payment
from . import res_config
from . import relationship_master
