from . import hostel_management
from . import category_master
from . import admission_form
from . import product_product
from . import student_details
from . import room_master
from . import room_type_master
from . import floor_master
from . import hostel_master
from . import hr_employee
from . import room_amenities_master
from . import room_allocation_master
