# -*- coding: utf-8 -*-
{
    'name': "Fees management",
    'summary': "Fees management",
    'description': "Fees management",
    'category': 'custom',
    'version': "16.0.0.1",
    'depends': ['base','mail','account','vg_colg','hostel_management'],
    'data': [
        'security/ir.model.access.csv',
        'security/fees_security.xml',
        'data/concession_data.xml',
        # 'data/one_time_fees_categ.xml',
        'data/account_move_data.xml',
        'wizard/reject_remarks_views.xml',
        'views/fees_management_views.xml',
        'views/one_time_fees_views.xml',
        'views/one_time_fees_category.xml',
        'views/concession_views.xml',
        'views/fees_for_master_views.xml',
        'views/student_onetime_fees.xml',
        'views/account_move_view.xml',
        'views/student_details.xml',
        'views/mode_of_payment.xml',
        'views/account_payment.xml',
        'wizard/concession_rejection_wizard.xml',
        'wizard/student_concession_report_wizard.xml',
        'wizard/report_wizard.xml',
        'wizard/payment_consolidated_report_wizard.xml',
        'wizard/daily_detailed_collection_report_wizard.xml',
        'wizard/daily_detailed_payment_report_wizard.xml',
        'report/student_approved_concession_report.xml',
        'report/student_rejected_concession_report.xml',
        'report/account_move_line.xml',
        'report/daily_collection_report.xml',
        'report/fee_payment_report.xml',
        'report/payment_consolidated_report.xml',
        'report/daily_detailed_collection_report.xml',
        'report/daily_detailed_payment_report.xml',
    ],

    'installable': True,
    'application': False,
}
