# -*- coding: utf-8 -*-
{
    'name': "Student Admission",
    'summary': "Student Admission",
    'description': "Student Adimision",
    'category': 'custom',
    'version': "16.0.0.1",
    'depends': ['website','account','web','l10n_in','document_management','mail'],
    'data': [

        'data/student_sequence.xml',
        'data/payment_method_data.xml',
        # 'data/community_data.xml',
        # 'data/courses_data.xml',
        'data/website_menu.xml',
        # 'data/district_data.xml',
        # 'data/grade_data.xml',
        'data/product_data.xml',
        # 'data/degree_data.xml',
        'data/welcome_mail_template.xml',
        'data/student_details.xml',
        'data/ir_action_data.xml',
        'data/document_varification.xml',
        # 'data/quota_data.xml',
        # 'data/semester_data.xml',
        # 'data/batch_data.xml',
        # 'data/stream_data.xml',
        # 'data/degree_level_data.xml',

        'security/ir.model.access.csv',
        'security/student_admission_security.xml',

        'reports/admission_report.xml',
        'reports/admission_concession_report.xml',

        'views/student_admission_view.xml',
        'views/create_website_student_admission.xml',
        'views/community_master_view.xml',
        'views/courses_master_view.xml',
        'views/district_master_view.xml',
        'views/institution_group_master_view.xml',
        'views/last_studied_institutions_view.xml',
        'views/place_city_master_view.xml',
        'views/reference_master_view.xml',
        'views/taluk_master_view.xml',
        'views/courses_and_college_master_view.xml',
        'views/degree_level_master.xml',
        'views/batch_master_view.xml',

        'wizard/admission_report_view.xml',
        'wizard/inquiry_transfer_views.xml',
        'wizard/transfer_college_view.xml',
        'wizard/transfer_courses_view.xml',
        'wizard/onhold_remarks_views.xml',
        'wizard/admission_concession_report_wizard.xml',
        'wizard/move_to_alumini.xml',
        'wizard/mail_notification_view.xml',
        'wizard/payment_notification_view.xml',

        'views/admission_confirmation_view.xml',
        'views/stages_master_view.xml',
        'views/account_move_view.xml',
        'views/grade_master_view.xml',
        'views/degree_master_view.xml',
        'views/student_details_views.xml',
        'views/token_fees.xml',
        'views/admission_list.xml',
        'views/section_master_view.xml',
        'views/stream_master.xml',
        'views/semester_master_view.xml',
        'views/quota_master_view.xml',
        'views/product_views.xml',
        'views/account_payment.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'vg_colg/static/src/js/student_admission.js',
        ],
    },
    'installable': True,
    'application': False,
}
